### PR TITLE
refactor: commonjs require understands json files

### PR DESCRIPTION
**Pull request by focusaurus**
Sticking an `index.json` file in the package root directory is sufficient for node to find and parse the JSON. The `require()` function understands both js and json files directly.

### CODE REVIEW

**Comment by aldeed** [comment]
Cool! I'll merge this, which will trigger NPM publish. If we then update one of the projects to use the new version and it still picks up the proper config, we're good. If not, we can revert this.

**Comment by aldeed** [comment]
Actually the only commit uses `refactor:`, so that might not trigger a publish.

**Comment by focusaurus** [comment]
Yeah I also added `[skip release]` to reduce noise. Next time we make an actual change, we'll see for certain whether this works but I'm confident it's correct.

**Pull request merged**
